# These are supported funding model platforms

github: [schoolrail]
patreon: schoolrail
open_collective: schoolrail
ko_fi: schoolrail
liberapay: schoolrail
custom:
  - https://www.buymeacoffee.com/schoolrail
  - https://paypal.me/schoolrail
