# These are supported funding model platforms

# These are supported funding model platforms
# Replace with your own usernames to accept donations
github: []
patreon: 
open_collective: 
ko_fi: 
liberapay: 
custom: []
