resource "aws_security_group" "rabbitmq" {
  name        = "${var.identifier}-rabbitmq-sg"
  description = "RabbitMQ security group"
  vpc_id      = var.vpc_id

  ingress {
    from_port       = 5671
    to_port         = 5672
    protocol        = "tcp"
    security_groups = var.allowed_security_groups
  }

  ingress {
    from_port       = 15671
    to_port         = 15672
    protocol        = "tcp"
    security_groups = var.allowed_security_groups
  }

  ingress {
    from_port       = 4369
    to_port         = 4369
    protocol        = "tcp"
    security_groups = var.allowed_security_groups
  }

  ingress {
    from_port       = 25672
    to_port         = 25672
    protocol        = "tcp"
    security_groups = var.allowed_security_groups
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = var.tags
}

resource "aws_mq_broker" "rabbitmq" {
  count = var.deployment_type == "amazon_mq" ? 1 : 0

  broker_name        = var.identifier
  engine_type        = "RabbitMQ"
  engine_version     = var.rabbitmq_version
  host_instance_type = var.instance_type
  deployment_mode    = var.multi_az ? "CLUSTER_MULTI_AZ" : "SINGLE_INSTANCE"

  subnet_ids = var.multi_az ? var.subnet_ids : [var.subnet_ids[0]]
  security_groups = [aws_security_group.rabbitmq.id]

  authentication_strategy = "simple"
  publicly_accessible     = false

  maintenance_window_start_time {
    day_of_week = "SUNDAY"
    time_of_day = "05:00"
    time_zone   = "UTC"
  }

  logs {
    general = true
    audit   = false
  }

  encryption_options {
    use_aws_owned_key = true
  }

  tags = var.tags
}

resource "random_password" "rabbitmq_admin" {
  length  = 32
  special = false
}

resource "aws_ssm_parameter" "rabbitmq_admin_password" {
  count = var.deployment_type == "amazon_mq" ? 1 : 0

  name  = "/${var.identifier}/rabbitmq/admin-password"
  type  = "SecureString"
  value = random_password.rabbitmq_admin.result

  tags = var.tags
}

resource "aws_mq_configuration" "rabbitmq" {
  count = var.deployment_type == "amazon_mq" ? 1 : 0

  name           = "${var.identifier}-config"
  engine_type    = "RabbitMQ"
  engine_version = var.rabbitmq_version

  data = <<-DATA
    consumers_timeout = 1800000
    heartbeat = 60
    default_queue_type = quorum
    cluster_keepalive_interval = 10000
    queue_master_locator = min-masters
    channel_max = 2048
    max_message_size = 134217728
    vm_memory_high_watermark = 0.8
    collect_statistics = coarse
  DATA
}

resource "kubernetes_namespace" "rabbitmq" {
  count = var.deployment_type == "eks" ? 1 : 0

  metadata {
    name = "${var.identifier}-rabbitmq"
  }
}

resource "helm_release" "rabbitmq" {
  count = var.deployment_type == "eks" ? 1 : 0

  name       = var.identifier
  namespace  = "${var.identifier}-rabbitmq"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "rabbitmq"
  version    = var.helm_chart_version

  values = [
    <<-VALUES
    auth:
      username: ${var.admin_user}
      password: ${var.admin_password}
    clustering:
      enabled: true
      rebalance: true
    metrics:
      enabled: true
      plugins: rabbitmq_prometheus
    persistence:
      enabled: true
      size: ${var.storage_size}
    plugins: rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_prometheus,rabbitmq_shovel,rabbitmq_federation
    tls:
      enabled: true
      autoGenerated: true
    resources:
      requests:
        memory: ${var.resources_requests_memory}
        cpu: ${var.resources_requests_cpu}
      limits:
        memory: ${var.resources_limits_memory}
        cpu: ${var.resources_limits_cpu}
    autoscaling:
      enabled: true
      minReplicas: ${var.min_replicas}
      maxReplicas: ${var.max_replicas}
      targetMemoryUtilizationPercentage: 70
    livenessProbe:
      enabled: true
    readinessProbe:
      enabled: true
    VALUES
  ]

  depends_on = [kubernetes_namespace.rabbitmq]
}

output "amqp_endpoint" {
  value = var.deployment_type == "amazon_mq" ? try(aws_mq_broker.rabbitmq[0].instances[0].endpoints[0], "") : ""
}

output "amqps_endpoint" {
  value = var.deployment_type == "amazon_mq" ? try(aws_mq_broker.rabbitmq[0].instances[0].endpoints[1], "") : ""
}

output "console_url" {
  value = var.deployment_type == "amazon_mq" ? try(aws_mq_broker.rabbitmq[0].instances[0].console_url, "") : ""
}

output "security_group_id" {
  value = aws_security_group.rabbitmq.id
}

output "helm_release_name" {
  value = var.deployment_type == "eks" ? try(helm_release.rabbitmq[0].name, "") : ""
}

output "helm_namespace" {
  value = var.deployment_type == "eks" ? "${var.identifier}-rabbitmq" : ""
}

variable "identifier" {
  type = string
}

variable "vpc_id" {
  type = string
}

variable "subnet_ids" {
  type = list(string)
}

variable "allowed_security_groups" {
  type = list(string)
}

variable "deployment_type" {
  type    = string
  default = "eks"

  validation {
    condition     = contains(["amazon_mq", "eks"], var.deployment_type)
    error_message = "deployment_type must be 'amazon_mq' or 'eks'."
  }
}

variable "rabbitmq_version" {
  type    = string
  default = "3.13"
}

variable "instance_type" {
  type    = string
  default = "mq.m5.large"
}

variable "multi_az" {
  type    = bool
  default = true
}

variable "admin_user" {
  type    = string
  default = "admin"
}

variable "admin_password" {
  type      = string
  sensitive = true
}

variable "helm_chart_version" {
  type    = string
  default = "14.3.0"
}

variable "storage_size" {
  type    = string
  default = "20Gi"
}

variable "resources_requests_memory" {
  type    = string
  default = "512Mi"
}

variable "resources_requests_cpu" {
  type    = string
  default = "250m"
}

variable "resources_limits_memory" {
  type    = string
  default = "2Gi"
}

variable "resources_limits_cpu" {
  type    = string
  default = "1"
}

variable "min_replicas" {
  type    = number
  default = 3
}

variable "max_replicas" {
  type    = number
  default = 10
}

variable "tags" {
  type    = map(string)
  default = {}
}
