{{- range .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .iamRole }}"
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/environment: {{ $.Values.global.environment }}
---
{{- end }}
