apiVersion: v2
name: api-gateway
description: Kong API Gateway for SchoolRail
type: application
version: 1.0.0
appVersion: "3.7"
keywords:
  - api-gateway
  - kong
  - schoolrail
home: https://github.com/PGMODE-CELL/schoolrail
sources:
  - https://github.com/PGMODE-CELL/schoolrail
maintainers:
  - name: SchoolRail Team
    email: devops@example.com
